name: Starter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'pnpm'

		- run: npm pkg delete scripts.prepare

		- name: Install dependencies
			run: pnpm i --frozen-lockfile

		- name: Linting
    	run: pnpm lint:ci

		- name: Type Checking
			run: pnpm type-check

		- name: Tests
			run: pnpm test:ci
